version: '3'
services:
  find_relatives_server:
    build: ./find_relatives_server
    volumes:
      - ./find_relatives_server:/find_relative
    ports:
      - 8080:8080 
    depends_on:
      - db
  
  db:
    image: mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD} 
    